name: Trigger auto deployment for container-app-3k7glrjidkzt6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-3k7glrjidkzt6-AutoDeployTrigger-146d0832-0dae-4da1-8d16-25be79239340.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP3K7GLRJIDKZT6_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP3K7GLRJIDKZT6_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP3K7GLRJIDKZT6_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP3K7GLRJIDKZT6_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP3K7GLRJIDKZT6_REGISTRY_PASSWORD }}
          containerAppName: container-app-3k7glrjidkzt6
          resourceGroup: expresssampleb3ed9f56
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


